export type MySQLInformationSchemaTableModel = {
  TABLE_CATALOG: string,
  TABLE_SCHEMA: string,
  TABLE_NAME: string,
  TABLE_TYPE: 'BASE TABLE' | 'VIEW' | 'SYSTEM VIEW' | string,
  ENGINE: string,
  VERSION: number,
  ROW_FORMAT: 'Dynamic' | 'Fixed' | 'Compressed' | 'Redundant' | 'Compact' | 'Paged' | string,
  TABLE_ROWS: number,
  AVG_ROW_LENGTH: number,
  DATA_LENGTH: number,
  MAX_DATA_LENGTH: number,
  INDEX_LENGTH: number,
  DATA_FREE: number,
  AUTO_INCREMENT: number,
  CREATE_TIME: Date | string,
  UPDATE_TIME: Date | string,
  CHECK_TIME: Date | string,
  TABLE_COLLATION: string,
  CHECKSUM: number,
  CREATE_OPTIONS: string,
  TABLE_COMMENT: string,
}

export type MySQLInformationSchemaColumnModel = {
  TABLE_CATALOG: string,
  TABLE_SCHEMA: string,
  TABLE_NAME: string,
  COLUMN_NAME: string,
  ORDINAL_POSITION: number,
  COLUMN_DEFAULT: string,
  IS_NULLABLE: 'YES' | 'NO' | string,
  DATA_TYPE: string,
  CHARACTER_MAXIMUM_LENGTH: number,
  CHARACTER_OCTET_LENGTH: number,
  NUMERIC_PRECISION: number,
  NUMERIC_SCALE: number,
  DATETIME_PRECISION: number,
  CHARACTER_SET_NAME: string,
  COLLATION_NAME: string,
  COLUMN_TYPE: string,
  COLUMN_KEY: 'PRI' | 'UNI' | 'MUL' | string,
  EXTRA: 'auto_increment' | string,
  PRIVILEGES: string,
  COLUMN_COMMENT: string,
  GENERATION_EXPRESSION: string,
  SRS_ID: number,
}
